name: Mirror to Github

on:
  push:
    branches: [ main ]
  delete:
  workflow_dispatch:

jobs:
  mirror:
    if: github.repository_owner == 'nicolas-georger'
    runs-on: academia

    steps:
      - name: tests-env
        shell: bash
        run: |
            uname -a || true
            env || true
            cat /etc/os-release

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Mirror to Github
        env:
          CUSTOM_GITHUB_USERNAME: ${{ secrets.CUSTOM_GITHUB_USERNAME }}
          CUSTOM_GITHUB_SECRET: ${{ secrets.CUSTOM_GITHUB_SECRET }}
        run: |
          git remote add github https://${{ secrets.CUSTOM_GITHUB_USERNAME }}:${{ secrets.CUSTOM_GITHUB_SECRET }}@github.com/Comunidad-IA-LATAM/tests.git
          git push --force --prune github \
            "refs/heads/*:refs/heads/*" \
            "refs/tags/*:refs/tags/*"